//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizTalkServiceClient.BTSService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://MyNameSpaceHere", ConfigurationName="BTSService.BizTalkWCF_AddSuffixService_RcvSuffixService")]
    public interface BizTalkWCF_AddSuffixService_RcvSuffixService {
        
        // CODEGEN: Generating message contract since the operation SuffixService is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="SuffixService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BizTalkServiceClient.BTSService.SuffixServiceResponse SuffixService(BizTalkServiceClient.BTSService.SuffixServiceRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalkWCF.Schemas.BizTalkServiceRequest")]
    public partial class Root : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private bool isAddSuffixField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool IsAddSuffix {
            get {
                return this.isAddSuffixField;
            }
            set {
                this.isAddSuffixField = value;
                this.RaisePropertyChanged("IsAddSuffix");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalkWCF.Schemas.BizTalkServiceResponse")]
    public partial class Root1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ResponseMessage {
            get {
                return this.responseMessageField;
            }
            set {
                this.responseMessageField = value;
                this.RaisePropertyChanged("ResponseMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SuffixServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BizTalkWCF.Schemas.BizTalkServiceRequest", Order=0)]
        public BizTalkServiceClient.BTSService.Root Root;
        
        public SuffixServiceRequest() {
        }
        
        public SuffixServiceRequest(BizTalkServiceClient.BTSService.Root Root) {
            this.Root = Root;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SuffixServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BizTalkWCF.Schemas.BizTalkServiceResponse", Order=0)]
        public BizTalkServiceClient.BTSService.Root1 Root;
        
        public SuffixServiceResponse() {
        }
        
        public SuffixServiceResponse(BizTalkServiceClient.BTSService.Root1 Root) {
            this.Root = Root;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BizTalkWCF_AddSuffixService_RcvSuffixServiceChannel : BizTalkServiceClient.BTSService.BizTalkWCF_AddSuffixService_RcvSuffixService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BizTalkWCF_AddSuffixService_RcvSuffixServiceClient : System.ServiceModel.ClientBase<BizTalkServiceClient.BTSService.BizTalkWCF_AddSuffixService_RcvSuffixService>, BizTalkServiceClient.BTSService.BizTalkWCF_AddSuffixService_RcvSuffixService {
        
        public BizTalkWCF_AddSuffixService_RcvSuffixServiceClient() {
        }
        
        public BizTalkWCF_AddSuffixService_RcvSuffixServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BizTalkWCF_AddSuffixService_RcvSuffixServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizTalkWCF_AddSuffixService_RcvSuffixServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizTalkWCF_AddSuffixService_RcvSuffixServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BizTalkServiceClient.BTSService.SuffixServiceResponse BizTalkServiceClient.BTSService.BizTalkWCF_AddSuffixService_RcvSuffixService.SuffixService(BizTalkServiceClient.BTSService.SuffixServiceRequest request) {
            return base.Channel.SuffixService(request);
        }
        
        public BizTalkServiceClient.BTSService.Root1 SuffixService(BizTalkServiceClient.BTSService.Root Root) {
            BizTalkServiceClient.BTSService.SuffixServiceRequest inValue = new BizTalkServiceClient.BTSService.SuffixServiceRequest();
            inValue.Root = Root;
            BizTalkServiceClient.BTSService.SuffixServiceResponse retVal = ((BizTalkServiceClient.BTSService.BizTalkWCF_AddSuffixService_RcvSuffixService)(this)).SuffixService(inValue);
            return retVal.Root;
        }
    }
}
